spring.application.name=spring-security-jwt
server.port=8090
spring.datasource.url=jdbc:postgresql://localhost:5432/springsecurity
spring.datasource.username=postgres
spring.datasource.password=Venky123!